version: '3.7'

services:
    zookeeper:
        hostname: zookeeper
        container_name: zookeeper
        image: confluentinc/cp-zookeeper
        ports:
            - "2181:2181"
        environment: 
            ZOOKEEPER_CLIENT_PORT: 2181

    kafka-broker:
        hostname: kafka-broker
        container_name: kafka-broker
        image: confluentinc/cp-kafka
        depends_on: 
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 500
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    mongo:
        image: mongo:latest
        container_name: mongo
        hostname: mongo
        ports:
            - 27001:27017
